### ISSUE TITLE
Failed integration test

### ISSUE THREAD

**Issue by mskyttner** [mskyttner/nub-docker#1]
One of the tests fail currently, it seems to be checklistbank.cli.importer.ImporterServiceIT.testStartUp that cannot connect to RabbitMQ.

The log says:

testStartUp(org.gbif.checklistbank.cli.importer.ImporterServiceIT)  Time elapsed: 4.545 sec  <<< ERROR!
java.io.IOException: null
    at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:67)
    at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:33)
    at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:343)
    at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:216)
    at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:118)
    at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:388)
    at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:516)
    at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:533)
    at org.gbif.common.messaging.DefaultMessagePublisher.<init>(DefaultMessagePublisher.java:74)
    at org.gbif.common.messaging.DefaultMessagePublisher.<init>(DefaultMessagePublisher.java:52)
    at org.gbif.checklistbank.cli.common.RabbitBaseService.startUp(RabbitBaseService.java:94)
    at org.gbif.checklistbank.cli.importer.ImporterService.startUp(ImporterService.java:84)
    at org.gbif.checklistbank.cli.importer.ImporterServiceIT.testStartUp(ImporterServiceIT.java:27)
Caused by: java.net.SocketException: Connection reset
    at java.net.SocketInputStream.read(SocketInputStream.java:209)
    at java.net.SocketInputStream.read(SocketInputStream.java:141)
    at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
    at java.io.DataInputStream.readUnsignedByte(DataInputStream.java:288)
    at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:95)
    at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:131)
    at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:515)

**Comment by mskyttner** [comment]
@Inkimar reported that this fixed
